name: helloworld

# trigger
on:
- push 

# jobs (ran sequentially here)
jobs:
    greetings:
        runs-on: ubuntu-latest
        steps:
        - id: s00
          run: echo "Current time is $(date)"
        - id: s01
          run: cat README.md

